// categoriesData.js
export const categoriesCards = [
  {
    type: "large",
    to: "/spa/paris",
    category: "spa",
    title: "Le Spa by Sothys Paris République 5*",
    description:
      "Le Spa Sothys, niché au sein du Renaissance Paris République Hotel, incarne l’exclusivité et le raffinement des rituels de bien-être.",
    image: "https://spa-prestige-collection.com/wp-content/uploads/2025/03/SPC-Essence-1975x1318-02.jpg",
    location: "75011 PARIS - ÎLE-DE-FRANCE - FRANCE",
    etablissement: "Spa",
    region: "Paris",
    service: "Bain à remous",
  },
  {
    type: "large",
    to: "/spa/occitanie",
    category: "sejour",
    title: "Hôtel Luxe Occitanie",
    description: "Un séjour raffiné au cœur de l’Occitanie avec spa privatif.",
    image: "https://picsum.photos/400/300?1",
    location: "31000 TOULOUSE - OCCITANIE - FRANCE",
    etablissement: "Hôtel",
    region: "Occitanie",
    service: "Bain Nordique",
  },
  {
    type: "large",
    to: "/spa/marseille",
    category: "coup-de-coeur",
    title: "Spa Méditerranée",
    description: "Détente et bien-être face à la mer à Marseille.",
    image: "https://picsum.photos/400/300?2",
    location: "13000 MARSEILLE - PROVENCE-ALPES-CÔTE D'AZUR - FRANCE",
    etablissement: "Spa",
    region: "Provence-Alpes-Côte d'Azur",
    service: "Bain à remous",
  },
  {
    type: "large",
    to: "/spa/paris",
    category: "sejour",
    title: "Hôtel Royal Paris",
    description: "Un hôtel cinq étoiles au cœur de la capitale.",
    image: "https://picsum.photos/400/300?3",
    location: "75008 PARIS - ÎLE-DE-FRANCE - FRANCE",
    etablissement: "Hôtel",
    region: "Paris",
    service: "Bain Nordique",
  },
  {
    type: "large",
    to: "/spa/lyon",
    category: "rituels",
    title: "Spa Montagne",
    description: "Relaxation et soins dans un cadre naturel à Lyon.",
    image: "https://picsum.photos/400/300?4",
    location: "69000 LYON - AUVERGNE-RHÔNE-ALPES - FRANCE",
    etablissement: "Spa",
    region: "Auvergne-Rhône-Alpes",
    service: "Bain à remous",
  },
  {
    type: "large",
    to: "/spa/nice",
    category: "sejour",
    title: "Hôtel Riviera Nice",
    description: "Vue panoramique sur la mer Méditerranée.",
    image: "https://picsum.photos/400/300?5",
    location: "06000 NICE - PROVENCE-ALPES-CÔTE D'AZUR - FRANCE",
    etablissement: "Hôtel",
    region: "Provence-Alpes-Côte d'Azur",
    service: "Bain Nordique",
  },
  {
    type: "large",
    to: "/spa/bordeaux",
    category: "visage",
    title: "Spa Vinothérapie",
    description: "Soins relaxants à base de raisin et vin de Bordeaux.",
    image: "https://picsum.photos/400/300?6",
    location: "33000 BORDEAUX - NOUVELLE-AQUITAINE - FRANCE",
    etablissement: "Spa",
    region: "Nouvelle-Aquitaine",
    service: "Bain à remous",
  },
  {
    type: "large",
    to: "/spa/lille",
    category: "corps",
    title: "Hôtel Grand Nord",
    description: "Confort et élégance au cœur de Lille.",
    image: "https://picsum.photos/400/300?7",
    location: "59000 LILLE - HAUTS-DE-FRANCE - FRANCE",
    etablissement: "Hôtel",
    region: "Hauts-de-France",
    service: "Bain Nordique",
  },
  {
    type: "large",
    to: "/spa/cannes",
    category: "spa",
    title: "Spa Côte d’Azur",
    description: "Luxe et sérénité sur la Côte d’Azur.",
    image: "https://picsum.photos/400/300?8",
    location: "06400 CANNES - PROVENCE-ALPES-CÔTE D'AZUR - FRANCE",
    etablissement: "Spa",
    region: "Provence-Alpes-Côte d'Azur",
    service: "Bain à remous",
  },
];